-- ============================
-- TABLES
-- ============================
CREATE TABLE IF NOT EXISTS public.projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text,
  description text,
  img text,
  link text,
  github text,
  features jsonb,
  tech_stack jsonb,
  is_published boolean DEFAULT true,
  order_index int DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.certificates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  img text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.portfolio_comments (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  content text NOT NULL,
  user_name text NOT NULL,
  profile_image text,
  is_pinned boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username text UNIQUE NOT NULL,
  role text NOT NULL CHECK (role IN ('admin', 'user')),
  created_at timestamptz DEFAULT now()
);

-- ============================
-- ADMIN SEED
-- ============================
INSERT INTO public.profiles (id, username, role)
VALUES ('de8a6767-b40f-4f72-8988-f28ede669e13', 'dwiki', 'admin')
ON CONFLICT (id) DO UPDATE
SET username = EXCLUDED.username,
    role = EXCLUDED.role;

-- ============================
-- ENABLE RLS
-- ============================
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portfolio_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- ============================
-- PUBLIC READ
-- ============================
DROP POLICY IF EXISTS "public read projects" ON public.projects;
CREATE POLICY "public read projects"
ON public.projects FOR SELECT
USING (true);

DROP POLICY IF EXISTS "public read certificates" ON public.certificates;
CREATE POLICY "public read certificates"
ON public.certificates FOR SELECT
USING (true);

DROP POLICY IF EXISTS "public read comments" ON public.portfolio_comments;
CREATE POLICY "public read comments"
ON public.portfolio_comments FOR SELECT
USING (true);

-- ============================
-- COMMENTS (USER)
-- ============================
DROP POLICY IF EXISTS "public insert comment" ON public.portfolio_comments;
CREATE POLICY "public insert comment"
ON public.portfolio_comments FOR INSERT
WITH CHECK (is_pinned = false);

-- ============================
-- ADMIN CHECK FUNCTION (BEST PRACTICE)
-- ============================
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
$$;

-- ============================
-- ADMIN POLICIES (PROJECTS)
-- ============================
DROP POLICY IF EXISTS "admin manage projects" ON public.projects;
CREATE POLICY "admin manage projects"
ON public.projects FOR ALL
USING (public.is_admin())
WITH CHECK (public.is_admin());

-- ============================
-- ADMIN POLICIES (CERTIFICATES)
-- ============================
DROP POLICY IF EXISTS "admin manage certificates" ON public.certificates;
CREATE POLICY "admin manage certificates"
ON public.certificates FOR ALL
USING (public.is_admin())
WITH CHECK (public.is_admin());

-- ============================
-- ADMIN POLICIES (COMMENTS)
-- ============================
-- UPDATE
DROP POLICY IF EXISTS "admin update comments" ON public.portfolio_comments;
CREATE POLICY "admin update comments"
ON public.portfolio_comments FOR UPDATE
USING (public.is_admin());

-- DELETE
DROP POLICY IF EXISTS "admin delete comments" ON public.portfolio_comments;
CREATE POLICY "admin delete comments"
ON public.portfolio_comments FOR DELETE
USING (public.is_admin());

-- ============================
-- PROFILES
-- ============================
DROP POLICY IF EXISTS "profiles read own" ON public.profiles;
CREATE POLICY "profiles read own"
ON public.profiles FOR SELECT
USING (auth.uid() = id);

-- ============================
-- STORAGE BUCKETS
-- ============================
INSERT INTO storage.buckets (id, name, public)
VALUES ('project-images', 'project-images', true)
ON CONFLICT DO NOTHING;

INSERT INTO storage.buckets (id, name, public)
VALUES ('certificate-images', 'certificate-images', true)
ON CONFLICT DO NOTHING;

-- ============================
-- STORAGE POLICIES
-- ============================
-- PROJECT IMAGES
DROP POLICY IF EXISTS "admin upload project images" ON storage.objects;
CREATE POLICY "admin upload project images"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'project-images'
  AND public.is_admin()
);

DROP POLICY IF EXISTS "public read project images" ON storage.objects;
CREATE POLICY "public read project images"
ON storage.objects FOR SELECT
USING (bucket_id = 'project-images');

-- CERTIFICATE IMAGES
DROP POLICY IF EXISTS "admin upload certificate images" ON storage.objects;
CREATE POLICY "admin upload certificate images"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'certificate-images'
  AND public.is_admin()
);

DROP POLICY IF EXISTS "public read certificate images" ON storage.objects;
CREATE POLICY "public read certificate images"
ON storage.objects FOR SELECT
USING (bucket_id = 'certificate-images');

-- ============================
-- CHECK ADMIN
-- ============================
SELECT id, username, role
FROM public.profiles
WHERE id = 'de8a6767-b40f-4f72-8988-f28ede669e13';